language: ruby
sudo: required
cache:
  bundler: true
  directories:
  - $ORACLE_DOWNLOAD_DIR
before_install:
- chmod +x .travis/sqlite3/extension-functions.sh
- chmod +x .travis/oracle/download.sh
- chmod +x .travis/oracle/install.sh
- chmod +x .travis/setup_accounts.sh
install:
- sudo apt-get install -y sqlite3-pcre curl freetds
- .travis/sqlite3/extension-functions.sh
- .travis/oracle/download.sh
- .travis/oracle/install.sh
- .travis/setup_accounts.sh
- gem install bundler
- bundle install
gemfile:
- gemfiles/rails4.gemfile
- gemfiles/rails5_0.gemfile
- gemfiles/rails5.gemfile
services:
- mysql
- postgresql
before_script:
- mysql -e 'create database arext_test;'
- psql -c 'create database arext_test;' -U postgres
script:
- gem build arel_extensions.gemspec
- bundle exec rake test
- bundle exec rake test:sqlite
- bundle exec rake test:mysql
- bundle exec rake test:postgresql
- bundle exec rake test:oracle # service unavailable
env:
  global:
  - JRUBY_OPTS='--dev -J-Xmx1024M'
  - ORACLE_COOKIE=sqldev
  - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
  - ORACLE_OJDBC_URL=http://download.oracle.com/otn/utilities_drivers/jdbc/11204/ojdbc6.jar
  - TNS_ADMIN=$ORACLE_HOME/network/admin
  - ORACLE_BASE=/u01/app/oracle
  - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
  - ORACLE_SID=XE
  - DATABASE_NAME=XE
  - NLS_LANG=AMERICAN_AMERICA.AL32UTF8
  - secure: 0RUuF4l0e3J8UIIMlgb8x/aYy2pH6Wb+EWylOr2W1EQechivoFw6IEYD1EZWIOZ/uNpkQ2h/urbUqW3/HpKhZn+NYP2sQI41Xyu1TD+6HPWAHpEvLzemhQSJV6eIeLRQoVDLUmqF23nUZDtKQAwOOyJVMeqHMahJi5K7N/cfQmifs2QcBnMxPnANIcrSXxOCBoqCl6BERG9JTeKERG/lWG1I9vRIe9ISNyOPUQVVI6SfTJwhJP5NLkxSJG1q2PLPK7p6zQ684sS4zSnS5oV23yDsQWWIwxk78CVu1jnFBu8Qq3ngWsInlkHrPotjtaxmTxM8JQd4fgE5NMO2Pjnj8w7zg+sbl+3OVtareX+M9+OLdUD5xBQhecPpzflMqib2qZ0fr9tdoT8kAZJTiXtQrptZfaXleZlH74l2dO/PYxkoWMusYQnSbQl0G3AoyYH+l7YpefL4arm0s5IIiOK+ZiCoZ14pl26rYAA1iPUe5AT+hecKi+fwqhyFE7fMX+zC+AvzsQL8jrP0CXL/hmPkoFYxvcDgUoYhvOq+mmQHdOfU7ny4hH5z5d9691qceduHFvF7fNZ4pSofj03eGqfTTk+SDNeZIo6NXNlayayjV2L/DxL6d7vetxkWwipx47PI76gBAqJlxgODJuzoOtyQkPyIVsDlzI1UPoS+UbrU51w=
rvm:
- 2.0.0
- 2.1
- 2.2.5
- 2.3.1
- 2.4.0
- rbx-2
- jruby-9.0.5.0
- jruby-head
- ruby-head
jdk:
- openjdk7
- oraclejdk8
matrix:
  fast_finish: true
  exclude:
  - rvm: rbx-2
    jdk: openjdk7
  - rvm: 2.0.0
    jdk: openjdk7
  - rvm: 2.1
    jdk: openjdk7
  - rvm: 2.2.5
    jdk: openjdk7
  - rvm: 2.3.1
    jdk: openjdk7
  - rvm: 2.4.0
    jdk: openjdk7
  - rvm: ruby-head
    jdk: openjdk7
  - rvm: 2.0.0
    gemfile: gemfiles/rails5.gemfile
  - rvm: 2.1
    gemfile: gemfiles/rails5.gemfile
  - rvm: rbx-2
    gemfile: gemfiles/rails5.gemfile
  - rvm: ruby-head
    gemfile: gemfiles/rails4.gemfile
  - rvm: 2.0.0
    gemfile: gemfiles/rails5_0.gemfile
  - rvm: 2.1
    gemfile: gemfiles/rails5_0.gemfile
  - rvm: rbx-2
    gemfile: gemfiles/rails5_0.gemfile
  allow_failures:
  - rvm: rbx-2
    gemfile: gemfiles/rails4.gemfile
  - rvm: rbx-2
    gemfile: gemfiles/rails5_0.gemfile
  - rvm: jruby-9.0.5.0
    gemfile: gemfiles/rails5_0.gemfile
  - rvm: jruby-head
    gemfile: gemfiles/rails5_0.gemfile
  - rvm: rbx-2
    gemfile: gemfiles/rails5.gemfile
  - rvm: jruby-9.0.5.0
    gemfile: gemfiles/rails5.gemfile
  - rvm: jruby-head
    gemfile: gemfiles/rails5.gemfile
bundler_args: "--jobs 3 --retry 2"
notifications:
  email: false
